services:
  PortfolioDashboard:
    image: docker.io/nomadmot/portfolio-dashboard:latest
    environment:
      - DATABASE_URI=sqlite://///home/appuser/investorlab/DATA/portfolio.db
      - DUCK_PUDDLE=/home/appuser/investorlab/DUCK_PUDDLE
      - LOGLEVEL_APPLICATION=INFO
      - LOGLEVEL_STREAMLIT=WARN
      - LOGLEVEL_SQLALCHEMY=WARN
      - YFINANCE_DEBUG=FALSE
      - SQLALCHEMY_ECHO=FALSE
      - SQLALCHEMY_ECHO_POOL=FALSE
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /path/to/your/data
        target: /home/appuser/investorlab