services:
  PortfolioDashboard:
    image: docker.io/nomadmot/portfolio-dashboard:latest
    environment:
      - DATABASE_URI=ducklake:/home/appuser/investorlab/DUCK_PUDDLE/portfolio.duckdb
      - DUCK_PUDDLE=/home/appuser/investorlab/DUCK_PUDDLE
      - LOGLEVEL_APPLICATION=INFO
      - LOGLEVEL_STREAMLIT=WARN
      - YFINANCE_DEBUG=FALSE
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /path/to/your/data
        target: /home/appuser/investorlab